@startuml

participant "Resource Owner"
participant "Client"
participant "Authorization Server"
participant "Resource Server"

"Resource Owner" -> "Client": Authenticate with Credentials
"Client" -> "Authorization Server": Access Token Request
activate "Authorization Server" #FFBBBB

rnote over "Authorization Server"
Needs
    //**client_id**//
    //**client_secret**//
    //**redirect_uri**//
    //**grant_type = <color #red>password</color>**//
    //**username**//
    //**password**//
endrnote

"Client" <-- "Authorization Server": Access Token [+ Refresh Token]
deactivate "Authorization Server"

loop

"Client" -> "Resource Server": Call API with Access Token
activate "Resource Server" #DarkSalmon
"Client" <-- "Resource Server": Response With Data
deactivate "Resource Server"

end


...subsequent as you wish ...

@enduml

