title: Lychee
author:
  name: barudisshu
  email: galudisu@gmail.com
description: A Jekyll blog.

url: "https://barudisshu.github.io"
theme: "lychee"

github:
  username: barudisshu # change to your github username

twitter:
  username: chenyanyi13 # change to your twitter username

social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: Galahad Fidel
  email: galudisu@gmail.com # change to your email address
  links:
    # The first element serves as the copyright owner's link
    - https://twitter.com/@chenyanyi13 # change to your twitter homepage
    - https://github.com/barudisshu # change to your github homepage
    # Uncomment below to add more social links
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

google_site_verification: # fill in to your verification string

# ↑ --------------------------
# The end of `jekyll-seo-tag` settings

google_analytics:
  id: # fill in your Google Analytics ID

# the avatar on sidebar, support local or CORS resources
avatar: assets/img/favicons/favicon-circle.svg

# boolean type, the global switch for TOC in posts.
toc: true


# Enable pagination
paginate: 10


# If you want to link only specific pages in your header, use this and add the path to the pages
# in order as they should show up.
header_pages:
  - about.md

# Set to `true` to show excerpts on the homepage.
#show_excerpts: false

# Lychee specific settings, which are only available from Lychee 3.0 onward.
lychee:
  # Lychee skin selection.
  # Available skins are:
  # classic	           Default, light color scheme.
  # dark	             Dark variant of the classic skin.
  # auto	             Adaptive skin based on the default classic and dark skins.
  # solarized-light	   Light variant of solarized color scheme.
  # solarized-dark	   Dark variant of solarized color scheme.
  # solarized	         Adaptive skin for solarized color scheme skins.
  skin: classic
  
  # Lychee date format.
  # The default value is "%b %d, %Y" (e.g. Nov 14, 2023) 
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #date_format: "%b-%d-%Y"

  # Generate social links in footer.
  #social_links:
  #  - { platform: devto,          user_url: "https://dev.to/jekyll" }
  #  - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
  #  - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
  #  - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
  #  - { platform: github,         user_url: "https://github.com/jekyll/lychee" }
  #  - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
  #  - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
  #  - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
  #  - { platform: linkedin,       user_url: "https://www.linkedin.com/in/jekyll" }
  #  - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
  #  - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
  #  - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
  #  - { platform: telegram,       user_url: "https://t.me/jekyll" }
  #  - { platform: twitter,        user_url: "https://twitter.com/jekyllrb" }
  #  - { platform: x,              user_url: "https://x.com/jekyllrb" }
  #  - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }


# uncomment baseurl if you want to publish the site to a subfolder
#baseurl: /blog
exclude:
  - LICENSE
  - README.adoc
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - .idea
asciidoc: { }
keep_files:
  - images
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    icons: font
    idseparator: _
    stylesdir: css
    imagedir: /images
    source-highlighter: coderay
